### ISSUE TITLE
Investigate errors from itextpdf when reading some pdfs

### ISSUE THREAD

**Issue by pgarrison** [pgarrison/speedreader#6]
Some stack traces:

java.lang.NoClassDefFoundError: org.bouncycastle.crypto.engines.AESFastEngine
at com.itextpdf.text.pdf.crypto.AESCipher.<init>(AESCipher.java:62)
at com.itextpdf.text.pdf.StandardDecryption.update(StandardDecryption.java:84)
at com.itextpdf.text.pdf.PdfEncryption.decryptByteArray(PdfEncryption.java:746)
at com.itextpdf.text.pdf.PdfString.decrypt(PdfString.java:218)
at com.itextpdf.text.pdf.PdfReader.readDecryptedDocObj(PdfReader.java:804)
at com.itextpdf.text.pdf.PdfReader.readDocObj(PdfReader.java:1152)
at com.itextpdf.text.pdf.PdfReader.readPdf(PdfReader.java:512)
at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:172)
at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:161)
at com.speedreader.Options$14.run(Options.java:448)

java.lang.NoClassDefFoundError: org.bouncycastle.crypto.engines.AESFastEngine
at com.itextpdf.text.pdf.crypto.AESCipher.<init>(AESCipher.java:62)
at com.itextpdf.text.pdf.StandardDecryption.update(StandardDecryption.java:84)
at com.itextpdf.text.pdf.PdfEncryption.decryptByteArray(PdfEncryption.java:746)
at com.itextpdf.text.pdf.PdfReader.getStreamBytesRaw(PdfReader.java:2365)
at com.itextpdf.text.pdf.PdfReader.getStreamBytes(PdfReader.java:2310)
at com.itextpdf.text.pdf.PdfReader.readObjStm(PdfReader.java:1215)
at com.itextpdf.text.pdf.PdfReader.readDocObj(PdfReader.java:1157)
at com.itextpdf.text.pdf.PdfReader.readPdf(PdfReader.java:512)
at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:172)
at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:161)
at com.speedreader.Options$14.run(Options.java:448)

**Comment by sathiyaselvam** [comment]
Add dependency jar,

<dependency>
    <groupId>com.itextpdf</groupId>
    <artifactId>itextpdf</artifactId>
    <version>5.5.4</version>
	<optional>true</optional>
</dependency>

<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.49</version>
</dependency>
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpkix-jdk15on</artifactId>
    <version>1.49</version>
</dependency>

**Comment by moonandroid** [comment]
ok
